twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site: Cotation
        facebook: https://facebook.com/
        twitter: https://twitter.com/
        google: https://plus.gloogle.com/
        linkedin: https://linkedin.com/
        devise: XAF

when@test:
    twig:
        strict_variables: true
