<?php

namespace App\Repository\Produit\Service;

use Doctrine\ORM\EntityRepository;
use App\Entity\Produit\Service\Pays;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends ServiceEntityRepository
{
	public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Pays::class);
    }

    public function add(Pays $entity, bool $flush = false): void
    {
        $this->getEntityManager()->persist($entity);

        if ($flush) {
            $this->getEntityManager()->flush();
        }
    }

	public function myfindAll()
	{
		$query = $this->createQueryBuilder('p')
					->orderBy('p.nom','ASC')
					->getQuery();
		return $query->getResult();
	}

	public function getSelectList()
	{
		$qb = $this->createQueryBuilder('p')
				->orderBy('p.nom','ASC');
		return $qb;
	}

	public function findPaysPagine($page, $nombreParPage)
	{
		if($page < 1){
			throw new \InvalidArgumentException('Page inexistant');
		}
		$query = $this->createQueryBuilder('p')
					->orderBy('p.nom','ASC')
					->getQuery();
		$query->setFirstResult(($page-1) * $nombreParPage)
			->setMaxResults($nombreParPage);
		return new Paginator($query);
	}
}
